// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Book struct {
	ID              int64
	Title           string
	Author          string
	PublicationDate sql.NullTime
	FinishedDate    sql.NullTime
	Rating          sql.NullString
}
