// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Book struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	Author       string    `json:"author"`
	FinishedDate time.Time `json:"finished_date"`
	Rating       string    `json:"rating"`
	UriThumbnail string    `json:"uri_thumbnail"`
	Review       string    `json:"review"`
}
