// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const addBook = `-- name: AddBook :exec
INSERT INTO books (title,author,publication_date,rating)
VALUES (?,?,?,?)
`

type AddBookParams struct {
	Title           string
	Author          string
	PublicationDate sql.NullTime
	Rating          sql.NullString
}

func (q *Queries) AddBook(ctx context.Context, arg AddBookParams) error {
	_, err := q.db.ExecContext(ctx, addBook,
		arg.Title,
		arg.Author,
		arg.PublicationDate,
		arg.Rating,
	)
	return err
}

const getAllBooks = `-- name: GetAllBooks :many
select id, title, author, publication_date, rating
from books
`

func (q *Queries) GetAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.PublicationDate,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
