// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"time"
)

const addBook = `-- name: AddBook :exec
INSERT INTO books (title,author,finished_date,rating,uri_thumbnail,review)
VALUES (?,?,?,?,?,?)
`

type AddBookParams struct {
	Title        string    `json:"title"`
	Author       string    `json:"author"`
	FinishedDate time.Time `json:"finished_date"`
	Rating       string    `json:"rating"`
	UriThumbnail string    `json:"uri_thumbnail"`
	Review       string    `json:"review"`
}

func (q *Queries) AddBook(ctx context.Context, arg AddBookParams) error {
	_, err := q.db.ExecContext(ctx, addBook,
		arg.Title,
		arg.Author,
		arg.FinishedDate,
		arg.Rating,
		arg.UriThumbnail,
		arg.Review,
	)
	return err
}

const deleteBookById = `-- name: DeleteBookById :exec
DELETE FROM books
where id=?
`

func (q *Queries) DeleteBookById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookById, id)
	return err
}

const getAllBooks = `-- name: GetAllBooks :many
select id, title, author, finished_date, rating, uri_thumbnail, review
from books
`

func (q *Queries) GetAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.FinishedDate,
			&i.Rating,
			&i.UriThumbnail,
			&i.Review,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookById = `-- name: GetBookById :one
SELECT id, title, author, finished_date, rating, uri_thumbnail, review
FROM books
WHERE id=?
LIMIT 1
`

func (q *Queries) GetBookById(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookById, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.FinishedDate,
		&i.Rating,
		&i.UriThumbnail,
		&i.Review,
	)
	return i, err
}

const getBooksByAuthor = `-- name: GetBooksByAuthor :many
SELECT id, title, author, finished_date, rating, uri_thumbnail, review
FROM books
WHERE author=?
`

func (q *Queries) GetBooksByAuthor(ctx context.Context, author string) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByAuthor, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.FinishedDate,
			&i.Rating,
			&i.UriThumbnail,
			&i.Review,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByAuthorSortedByFinishedDate = `-- name: GetBooksByAuthorSortedByFinishedDate :many
SELECT id, title, author, finished_date, rating, uri_thumbnail, review
FROM books
WHERE author=?
ORDER BY finished_date ASC
`

func (q *Queries) GetBooksByAuthorSortedByFinishedDate(ctx context.Context, author string) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByAuthorSortedByFinishedDate, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.FinishedDate,
			&i.Rating,
			&i.UriThumbnail,
			&i.Review,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByAuthorSortedByFinishedDatev2 = `-- name: GetBooksByAuthorSortedByFinishedDatev2 :many
SELECT id, title, author, finished_date, rating, uri_thumbnail, review
FROM books
WHERE author=?
ORDER BY finished_date DESC
`

func (q *Queries) GetBooksByAuthorSortedByFinishedDatev2(ctx context.Context, author string) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByAuthorSortedByFinishedDatev2, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.FinishedDate,
			&i.Rating,
			&i.UriThumbnail,
			&i.Review,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByAuthorSortedByPublicationDate = `-- name: GetBooksByAuthorSortedByPublicationDate :many
SELECT id, title, author, finished_date, rating, uri_thumbnail, review
FROM books
WHERE author=?
ORDER BY publication_date
`

func (q *Queries) GetBooksByAuthorSortedByPublicationDate(ctx context.Context, author string) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByAuthorSortedByPublicationDate, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.FinishedDate,
			&i.Rating,
			&i.UriThumbnail,
			&i.Review,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
